### ISSUE TITLE
Question - When user try to open the report "General Ledger" and "Trail Balance" then it shows the Odoo Error.

### ISSUE THREAD

**Issue by CodePracticergeek** [Mitwill/odoo-base#1]
When user try to open the report "General Ledger" and "Trail Balance" then it shows the Odoo Error.

Test Env - Test

Steps to reprodcued:
1) Login with the Valid user
2) Open the "Accounting Module"
3) Click on the "Reporting"
4) Select the General Ledger" or "Trail Balance" report

Expected result: Should be able to open the report

Actual result: Not able to open the report. Show odoo error as below:                                                                                                                                                                 

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1782, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1809, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2013, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/enterprise-addons/account_reports/models/account_report.py", line 4394, in get_report_information
    'lines': self._get_lines(options, all_column_groups_expression_totals=all_column_groups_expression_totals, warnings=warnings),
  File "/mnt/enterprise-addons/account_reports/models/account_report.py", line 2110, in _get_lines
    dynamic_lines = self._get_dynamic_lines(options, all_column_groups_expression_totals, warnings=warnings)
  File "/mnt/enterprise-addons/account_reports/models/account_report.py", line 2482, in _get_dynamic_lines
    return self.env[self.custom_handler_model_name]._dynamic_lines_generator(self, options, all_column_groups_expression_totals, warnings=warnings)
  File "/mnt/enterprise-addons/account_reports/models/account_trial_balance_report.py", line 38, in _dynamic_lines_generator
    lines = [line[1] for line in self.env['account.general.ledger.report.handler']._dynamic_lines_generator(report, options, all_column_groups_expression_totals, warnings=warnings)]
  File "/mnt/enterprise-addons/account_reports/models/account_general_ledger.py", line 46, in _dynamic_lines_generator
    for account, column_group_results in self._query_values(report, options):
  File "/mnt/enterprise-addons/account_reports/models/account_general_ledger.py", line 217, in _query_values
    groupby_accounts.setdefault(equity_unaffected_account.id, {col_group_key: {'unaffected_earnings': {}} for col_group_key in options['column_groups']})
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 5154, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: account.account(33, 32, 919)

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (https://test-eosenterprise.mitwilltextiles.com/web/assets/ad2d9ff/web.assets_web.min.js:916:101)
        at App.handleError (https://test-eosenterprise.mitwilltextiles.com/web/assets/ad2d9ff/web.assets_web.min.js:1551:29)
        at ComponentNode.initiateRender (https://test-eosenterprise.mitwilltextiles.com/web/assets/ad2d9ff/web.assets_web.min.js:1007:19)

Caused by: RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://test-eosenterprise.mitwilltextiles.com/web/assets/ad2d9ff/web.assets_web.min.js:2900:163)
        at XMLHttpRequest.<anonymous> (https://test-eosenterprise.mitwilltextiles.com/web/assets/ad2d9ff/web.assets_web.min.js:2904:13)

**Comment by CodePracticergeek** [comment]
@Jamufa can you please have a look into this.
